# Generated by Django 3.2 on 2022-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'In Progress')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bug'), (1, 'Feature'), (2, 'Task'), (3, 'User Story')], default=0),
        ),
    ]
