# Generated by Django 3.2 on 2022-02-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['priority', 'status']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='issue_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(choices=[(0, 'Personal Project'), (1, 'Team Project')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
