# Generated by Django 3.2 on 2022-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220211_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'Closed')], default=0),
        ),
    ]
